INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MENBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Guerra');
INSERT INTO tb_genre (name) VALUES ('Faroeste');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Ficção científica');

INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Raya e o Último Dragão ', 'O reino encantado Kumandra', 2021, 'https://www.themoviedb.org/t/p/w500_and_h282_face/rcUcYzGGicDvhDs58uM44tJKB9F.jpg', 'O reino encantado Kumandra é dividido em cinco regiões e sua população venerava os dragões mágicos que eram presentes no reino, porém quando uma força maligna ameaçou a Terra, os dragões se sacrificaram para salvar a humanidade. Agora, 500 anos depois, o mesmo mal voltou e cabe a uma guerreira solitária, Raya, rastrear o lendário último dragão para restaurar a terra fraturada e seu povo dividido.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Freaky: No Corpo de um Assassino ', 'Basic switch. Killer new look.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nalyUACCgsux5ccEI0HeeKOuTrf.jpg', 'Millie, uma estudante do último ano do ensino médio, está tentando sobreviver sendo a garota impopular quando se torna o próximo alvo de The Butcher, um serial killer. Seu encontro fatídico é distorcido e eles acordam um no corpo do outro.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Até o Último Homem ', 'Um dos maiores heróis da história americana nunca disparou uma bala.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6O0lsCK90jZCyPvyYSt8Szzlnd6.jpg', 'Desmond T. Doss, foi o médico do Exército Americano da Segunda Guerra Mundial, que serviu durante a Batalha de Okinawa, se recusando a matar pessoas, tornando-se o primeiro homem da história americana a receber a Medalha de Honra sem disparar um tiro.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Zona de Combate', 'Em um futuro próximo', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg', 'Em um futuro próximo, um piloto de drone e um androide ultrassecreto trabalham lado a lado no campo de batalha para evitar um ataque nuclear.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Corações de Ferro', 'Uma guerra nunca termina serenamente.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/gPcLCI8LmsOPCLPwwEoXj8lQ07R.jpg', 'Durante o final da Segunda Guerra Mundial, um grupo de cinco soldados americanos é encarregado de atacar os nazistas dentro da própria Alemanha. Apesar de estarem em quantidade inferior e terem poucas armas, eles são liderados pelo enfurecido Wardaddy (Brad Pitt), sargento que pretende levá-los à vitória, enquanto ensina o novato Norman (Logan Lerman) a lutar.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Sniper Americano', 'O atirador mais letal da história dos EUA.', 2014, 'https://www.themoviedb.org/t/p/original/p1OUTSc4w7979JaH1mSp4p2FgXQ.jpg', 'História real de Chris Kyle, atirador de elite das forças especiais da marinha dos Estados Unidos. Durante a guerra do Iraque, sua missão era uma só- proteger seus companheiros. Seu dever fez dele um dos maiores atiradores da história americana. Sua precisão salva inúmeras vidas, mas também o torna um alvo preferencial. Quando Kyle finalmente volta para casa, ele descobre que não tem como deixar a guerra para trás.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Relatos do Mundo', 'Encontre o seu lar.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fJyHzq0ZWmXj2HJZWqSxEu4rh3v.jpg', 'Um veterano de guerra que viaja de cidade em cidade lendo as notícias faz uma perigosa viagem pelo Texas para levar uma garotinha órfã até seu novo lar.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Violação ', 'Nas profundezas do espaço, eles não estão sozinhos.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg', 'À beira da paternidade, um mecânico júnior a bordo de uma arca interestelar para a Nova Terra deve superar um terror cósmico malévolo com a intenção de usar a nave espacial como uma arma.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Sete Homens e Um Destino', 'A justiça tem um número', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kjvxlzbQW7M0o0fQZRdFARMwlCd.jpg', 'Os habitantes de um pequeno vilarejo sofrem com os constantes ataques de um bando de pistoleiros. Revoltada com os saques, Emma Cullen deseja justiça e pede auxílio ao pistoleiro Sam Chisolm, que reúne um grupo de especialistas para contra-atacar os bandidos.', 4);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Greyhound - Na Mira do Inimigo', 'Greyhound - Na Mira do Inimigo', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1iDQif1eme8lMaNxozhzIUFIoKc.jpg', 'Em Greyhound: Na Mira do Inimigo, o comboio internacional de 37 navios aliados liderado pelo capitão Ernest Krause (Tom Hanks), que está em seu primeiro comando de destróier norte-americano, atravessa o temido Atlântico Norte e precisa enfrentar a perseguição por matilhas de submarinos nazistas.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Soul ', 'Joe Gardner é um professor de música de ensino fundamental', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7EslmAX1Pz0HGwpa8hnVAqiOWf9.jpg', 'Joe Gardner é um professor de música de ensino fundamental desanimado por não conseguir alcançar seu sonho de tocar no lendário clube de jazz The Blue Note, em Nova York. Quando um acidente o transporta para fora do seu corpo, fazendo com que ele exista em outra realidade na forma de sua alma, ele se vê forçado a embarcar em uma aventura ao lado da alma de uma criança que ainda está aprendendo sobre si, para aprender o que é necessário para retomar sua vida.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Tom & Jerry - O Filme', 'Melhores inimigos. Piores amigos.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fev8UFNFFYsD5q7AcYS8LyTzqwl.jpg', 'Um gato de rua chamado Tom é contratado por uma garota chamada Kayla, uma jovem empregada que trabalha em um hotel glamouroso em Nova York, para se livrar de Jerry, um rato travesso que se mudou para o hotel, antes que ele seja a ruína de um importante casamento.', 5);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Miraculous World: Nova Iorque, Heróis Unidos', 'NEW CITY. SAME DUTY.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg', 'A turma de Marinette (Cristina Valenzuela) embarca numa viagem para Nova York com o intuito de comemorar a semana franco-americana da amizade. Ladybug então deixa Paris sob os cuidados de Cat Noir (Bryce Papenbrook), que fica em uma situação complicada já que Adrien foi chamado para a viagem. No entanto, o maior problema será um colar de garras de águia extremamente poderoso que está na mira de Hawk Moth (Keith Silverstein). Nesse momento, Ladybug terá que se unir aos heróis americanos para proteger a cidade que nunca dorme.Thomas Astruc', 5);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Nova Ordem Espacial', '2092, the space sweep begins!', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/drulhSX7P5TQlEMQZ3JoXKSDEfz.jpg', 'Perseguindo detritos espaciais e sonhos distantes no ano de 2092, quatro desajustados descobrem segredos explosivos durante a tentativa de comércio de um humanoide.‎', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Godzilla vs. Kong', 'Um dos dois cairá.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iopYFB1b6Bh7FWZh3onQhph1sih.jpg', 'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Code 8: Renegados', 'Fear is the most dangerous power', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wlnDNMQlnwl5ETlVY6n9CEtR5s0.jpg', 'Num mundo onde pessoas com habilidades “especiais” vivem na pobreza, Conner Reed é um jovem poderoso que está a lutar para pagar pelo tratamento médico da sua mãe doente. Para ganhar dinheiro, ele entra num mundo criminoso e lucrativo, liderado por Garrett, que trabalha para um traficante de drogas.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Skylines', 'To save our world she must invade theirs.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg', 'Quando um vírus ameaça transformar os híbridos alienígenas amigáveis que agora vivem na Terra contra os humanos, a capitã Rose Corley deve liderar uma equipe de mercenários de elite em uma missão ao mundo alienígena para salvar o que resta da humanidade.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Tenet', 'O tempo acaba.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wzJRB4MKi3yK138bJyuL9nx47y6.jpg', 'Armado com apenas uma palavra – Tenet – e lutando pela sobrevivência do mundo inteiro, o Protagonista viaja através de um mundo crepuscular de espionagem internacional em uma missão que irá desenrolar em algo para além do tempo real.', 6);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('1917 ', 'O tempo é o maior inimigo.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tJgmraUAmVlJPlq72yC76tKDyC4.jpg', 'Os cabos Schofield (George MacKay) e Blake (Dean-Charles Chapman) são jovens soldados britânicos durante a Primeira Guerra Mundial. Quando eles são encarregados de uma missão aparentemente impossível, os dois precisam atravessar território inimigo, lutando contra o tempo, para entregar uma mensagem que pode salvar cerca de 1600 colegas de batalhão.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('O Resgate do Soldado Ryan', 'A missão é um homem.', 1998, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3E5pvJLNEz5WmYWl6GfFW8hEVV3.jpg', 'Ao desembarcar na Normandia, no dia 6 de junho de 1944, capitão Miller (Tom Hanks) recebe a missão de comandar um grupo do segundo batalhão para o resgate do soldado James Ryan, caçula de quatro irmãos, dentre os quais três morreram em combate. Por ordens do chefe George C. Marshall, eles precisam procurar o soldado e garantir o seu retorno, com vida, para casa.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Falcão Negro em Perigo ', 'Nenhum homem será deixado para trás.', 2001, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rVMoexBm4aMN5hEOt8f3mJTtk9I.jpg', 'Em outubro de 1993, durante a guerra civil da Somália, uma força de elite americana é enviada para capturar generais locais. Porém, após dois helicópteros serem derrubados, o que deveria ser uma operação simples se torna uma extensa batalha.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Guerra ao Terror', 'Para um grupo de soldados o perigo não estava somente no campo de batalha.', 2008, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9UAhRDffrWkOwxqzqAF6ls1iEZ8.jpg', 'JT Sanborn, Owen Eldridge e Matt Thompson integram o esquadrão antibombas do exército americano em missão no Iraque. Eles trabalham na destruição de um explosivo, para que seja detonado sem atingir alguém. Entretanto, um erro faz com que o artefato exploda e mate Thompson. Em seu lugar é enviado o sargento William James, que possui muito sangue-frio, o que incomoda Sanborn. Apesar disto, o trio segue na ativa, tendo consciência de que cada dia concluído de trabalho é um dia a mais de vida.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('A Hora Mais Escura ', 'A maior caçada humana da história, em busca do homem mais perigoso do mundo.', 2012, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9d2RSOBmA5k6sDQoOkuBxJ9Gf7h.jpg', 'Maya é uma agente da CIA que está por trás dos principais esforços em capturar Osama bin Laden, por ter descoberto os interlocutores do líder do grupo terrorista. Com isso ela participa da operação que levou militares americanos a invadir o território paquistanês, com o objetivo de capturar e matar bin Laden.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Bad Boys Para Sempre ', 'Sempre juntos. Até o final.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eNkeLslgV9apdxcLYM45NNuwvaJ.jpg', 'Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_uri, synopsis, genre_id) VALUES ('Projeto Gemini', 'Quem pode salvá-lo de você mesmo.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/c3F4P2oauA7IQmy4hM0OmRt2W7d.jpg', 'Henry Brogan é um assassino de elite que se torna o alvo de um agente misterioso que aparentemente pode prever todos os seus movimentos. Ele logo descobre que o homem que está tentando matá-lo é uma versão mais jovem, rápida e clonada de si mesmo.', 1);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Melhor desenho da Disney de longe. Milhares de referências, super dinâmico, quase duas horas de filme. Milgrau', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Achei o filme muito bom, historia boa, atores ótimos, mas não tem praticamente nenhuma trilha sonora. ', 2, 6);
